# Basic
title: Welcome
subtitle: DLY's Blog
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
#description: This is personnal blog.
creator: <a href="https://github.com/dd-dly">@dly</a>

url: "https://github.com/dd-dly/dd-dly.github.io"

permalink: /:year/:month/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "posts"
      title: "DLY Blog"

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Github, description: My Github, url: 'https://github.com/dd-dly/dd-dly.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: dly
    # duoshuo: 
    
# Social
social:
#    weibo: onevcat
    github: dd-dly
#    twitter: onevcat
#    gplus: 107108267983477358170
    mail: xiaodeng341@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
theme: jekyll-theme-leap-day
